# mkdocs.yml
site_name : ChemSage Datafile format and parsing
site_url: https://evnekdev.github.io/chemsage-datafile-docs/


extra_css:
  - stylesheets/extra.css
  
theme:
  name: material
  
nav:
  - Home :
    - Overview : index.md
    - Theoretical basis: theory.md
  